package io.guide.localdynamodbandmssql.dynamodb;
import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.Arrays;
import java.util.Objects;

@DynamoDBTable(tableName = "DynamoStudent")
public class DynamoStudent {

    private String id;
    private String firstName;
    private String lastName;

    public DynamoStudent() {
        // Default constructor is required by AWS DynamoDB SDK
    }

    public DynamoStudent(String firstName, String lastName) {
        this.firstName = firstName;
        this.lastName = lastName;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getFirstName() {
        return firstName;
    }

    @DynamoDBAttribute
    public String getLastName() {
        return lastName;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    //setter & hashCode & equals
    @Override
    public String toString() {
        return "User [id=" + id + ", firstName=" + firstName + ", lastName=" + lastName + "]";
    }

    @Override
    public int hashCode() {
        return Objects.hash(firstName, id, lastName);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        DynamoStudent other = (DynamoStudent) obj;
        return Arrays.deepEquals(new Object[]{firstName, id, lastName},
                new Object[]{other.firstName, other.id, other.lastName});
    }
}